# Generated by Django 5.1.3 on 2024-11-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=25)),
                ('mobile', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
